### ISSUE TITLE
Support node 0.8

### ISSUE THREAD

**Issue by Raynos** [Matt-Esch/opentty#1]
This doesn't open a stream in node 0.8

or at least it's either paused by default or the program just exists.

**Comment by Matt-Esch** [comment]
the stream is paused by default in 0.8.

**Comment by Raynos** [comment]
hmm, do you have a recommendation on how to check for that edge case?

Maybe just do `var tty = opentty(); tty.resume();` always ?

**Comment by Matt-Esch** [comment]
Seems like a reasonable solution, I had already tried and tested that so I've updated it.
